# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Eye-Remocon Tech Blog
tagline:             Home Edge Project
description:         Eye-Remocon
url:                 https://eye-remocon.github.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Eye-Remocon
  url:               https://eye-remocon.github.com
  email:             hithere1012@naver.com

# Custom vars
version:             1.0.0

plugins: [jekyll-paginate]

# Tag setting
#collections:
#  tags:
#    output: true
#    permalink: /tags/:path/

#defaults:
#  - scope:
#      path: ''
#      type: tags
#    values:
#      layout: tag

google_analytics:
  ua: 'UA-109898110-1'

github:
  repo: 'https://github.com/Eye-Remocon/Eye-Remocon.github.io'
  meetingrepo:      'https://github.com/Eye-Remocon/MeetingNote'


category_dir: category/
tag_dir: tag/

excerpt_separator: ""
